config/routes.rb
Rails.application.routes.draw do

resources :teams
resources :leagues
resources :league_clients
resources :league_wagers
resources :secrets
resources :players
resources :pools
resources :groups
resources :selections
resources :tickets


get "users/profile" => "welcome#users_show"
get "game/rules" => "welcome#rules"










devise_for :users, :controllers => { :registrations => 'users/registrations' }
devise_scope :user do
  authenticated :user do
    root :to => "welcome#users_show", as: :authenticated_root
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/league.rb
class League < ApplicationRecord
	has_many :league_clients
	has_many :league_wagers

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

	def new

		@league = League.new
		
	end

	def create

		league = League.new(league_params)

		if league.save
			
			redirect_to leagues_path
		
		else

			render new_league_path

		end
	


	end

	def index


		@secret = Secret.new

		@leagues = League.all

		@league = League.new



	end

	def show

		@league = League.find_by_id(params[:id])
		@client = LeagueClient.new
		@league_id = @league.id
		@users = User.all



	end

	

	private

	def league_params

	params.require(:league).permit(:pass, :clients, :league_name, :start_date, :end_date)

	end

	def league_client_params

		params.require(:league_client).permit(:user_id, :league_id, :league_name, :stakes, :bet_types, :sports, :wager_limit)

	end

	def secret_params

		params.require(:secret).permit(:pass, :date, :user_id)

	end
end

app/helpers/leagues_helper.rb
module LeaguesHelper

	def check_end_date

		if @month_chk == "Jan"

			@month_chk = "01"

		elsif @month_chk == "Feb"

			@month_chk = "02"

		elsif @month_chk == "Mar"

			@month_chk = "03"

		elsif @month_chk == "Apr"

			@month_chk = "04"

		elsif @month_chk == "May"

			@month_chk = "05"

		elsif @month_chk == "Jun"

			@month_chk = "06"

		elsif @month_chk == "Jul"

			@month_chk = "07"

		elsif @month_chk == "Aug"

			@month_chk = "08"

		elsif @month_chk == "Sep"

			@month_chk = "09"

		elsif @month_chk == "Oct"

			@month_chk = "10"

		elsif @month_chk == "Nov"

			@month_chk = "11"

		elsif @month_chk == "Dec"

			@month_chk = "12"

		end

		@end_date_ser = @year_chk + @month_chk + @day_chk  
		@end_date_ser = @end_date_ser.to_i


	end

	def check_start_date

		if @month_chk == "Jan"

			@month_chk = "01"

		elsif @month_chk == "Feb"

			@month_chk = "02"

		elsif @month_chk == "Mar"

			@month_chk = "03"

		elsif @month_chk == "Apr"

			@month_chk = "04"

		elsif @month_chk == "May"

			@month_chk = "05"

		elsif @month_chk == "Jun"

			@month_chk = "06"

		elsif @month_chk == "Jul"

			@month_chk = "07"

		elsif @month_chk == "Aug"

			@month_chk = "08"

		elsif @month_chk == "Sep"

			@month_chk = "09"

		elsif @month_chk == "Oct"

			@month_chk = "10"

		elsif @month_chk == "Nov"

			@month_chk = "11"

		elsif @month_chk == "Dec"

			@month_chk = "12"

		end

		@start_date_ser = @year_chk + @month_chk + @day_chk  
		@start_date_ser = @start_date_ser.to_i


	end

	def convert_my_date

		@my_month = @my_date[3] + @my_date[4] + @my_date[5] 

		if @my_month == "Jan"

			@my_month = "01"

		elsif @my_month == "Feb"

			@my_month = "02"

		elsif @my_month == "Mar"

			@my_month = "03"

		elsif @my_month == "Apr"

			@my_month = "04"

		elsif @my_month == "May"

			@my_month = "05"

		elsif @my_month == "Jun"

			@my_month = "06"

		elsif @my_month == "Jul"

			@my_month = "07"

		elsif @my_month == "Aug"

			@my_month = "08"

		elsif @my_month == "Sep"

			@my_month = "09"

		elsif @my_month == "Oct"

			@my_month = "10"

		elsif @my_month == "Nov"

			@my_month = "11"

		elsif @my_month == "Dec"

			@my_month = "12"

		end

		@my_date = @my_date[7] + @my_date[8] + @my_date[9] + @my_date[10] + @my_month + @my_date[0] + @my_date[1] 
		@my_date = @my_date.to_i


	end

	def create_league_wager(obj)

		@bet_type = " "

		if obj.stakes == "small timer"

			@amount_arr = [50, 75, 100]
			@amount = @amount_arr.sample

		elsif obj.stakes == "pay dumper"

			@amount_arr = [200, 250, 300]
			@amount = @amount_arr.sample

		elsif obj.stakes == "whale"

			@amount_arr = [500, 1000, 2000]
			@amount = @amount_arr.sample

		end


		if obj.bet_types == "All"

			if @teaser_options.to_i > 4

				@bet_opt = ["straight", "two team teaser", "straight", "three team teaser", "five team teaser", "three team parlay", "two team parlay", "straight", "five team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options.to_i == 4 && @all_other_options.to_i > 4

				@bet_opt = ["straight", "two team teaser", "straight", "three team teaser", "five team teaser", "three team parlay", "two team parlay", "straight", "five team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options.to_i == 4 && @all_other_options.to_i == 4

				@bet_opt = ["straight", "two team teaser", "straight", "three team teaser", "three team parlay", "two team parlay", "straight", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options.to_i == 3 && @all_other_options.to_i > 4 

				@bet_opt = ["straight", "two team teaser", "straight", "three team teaser", "three team parlay", "five team parlay", "two team parlay", "straight", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options.to_i == 3 && @all_other_options.to_i == 4

				@bet_opt = ["straight", "two team teaser", "straight", "three team teaser", "three team parlay", "two team parlay", "straight", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample 

			elsif @teaser_options.to_i == 3 && @all_other_options == 3

				@bet_opt = ["straight", "two team teaser", "straight", "three team teaser", "three team parlay", "two team parlay", "straight", "two team reverse", "three team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options == 2 && @all_other_options > 4

				@bet_opt = ["straight", "two team teaser", "straight", "three team parlay", "five team parlay", "two team parlay", "straight", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options == 2 && @all_other_options == 4

				@bet_opt = ["straight", "two team teaser", "straight", "three team parlay", "two team parlay", "straight", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options == 2 && @all_other_options == 3

				@bet_opt = ["straight", "two team teaser", "straight", "three team parlay", "two team parlay", "straight", "two team reverse", "three team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options == 2 && @all_other_options == 2

				@bet_opt = ["straight", "two team teaser", "two team parlay", "two team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options == 0

				if @all_other_options == 2

					@bet_opt = ["straight", "two team parlay", "two team reverse"]
					@bet_type = @bet_opt.sample

				elsif @all_other_options == 3

					@bet_opt = ["straight", "three team parlay", "two team parlay", "straight", "two team reverse", "three team reverse"]
					@bet_type = @bet_opt.sample
				
				elsif @all_other_options == 4

					@bet_opt = ["straight", "straight", "three team parlay", "two team parlay", "two team reverse", "three team reverse", "four team reverse"]
					@bet_type = @bet_opt.sample
				
				elsif @all_other_options > 4

					@bet_opt = ["straight", "straight", "three team parlay", "two team parlay", "five team parlay", "two team reverse", "three team reverse", "four team reverse"]
					@bet_type = @bet_opt.sample

				end


			end

		elsif obj.bet_types == "Exotics"

			if @teaser_options.to_i > 4

				@bet_opt = [ "two team teaser", "three team teaser", "five team teaser", "three team parlay", "two team parlay", "five team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options == 4 && @all_other_options > 4

				@bet_opt = ["two team teaser", "three team teaser", "five team teaser", "three team parlay", "two team parlay", "five team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options == 4 && @all_other_options == 4

				@bet_opt = ["two team teaser", "three team teaser", "three team parlay", "two team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options == 3 && @all_other_options > 4

				@bet_opt = ["two team teaser", "three team teaser", "three team parlay", "five team parlay", "two team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample 
			
			elsif @teaser_options == 3 && @all_other_options == 4 

				@bet_opt = ["two team teaser", "three team teaser", "three team parlay", "two team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample 

			elsif @teaser_options == 3 && @all_other_options == 3

				@bet_opt = ["two team teaser", "three team teaser", "three team parlay", "two team parlay", "two team reverse", "three team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options == 2 && @all_other_options > 4

				@bet_opt = ["two team teaser", "three team parlay", "five team parlay", "two team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options == 2 && @all_other_options == 4

				@bet_opt = ["two team teaser", "three team parlay", "two team parlay", "two team reverse", "three team reverse", "four team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options == 2 && @all_other_options == 3

				@bet_opt = ["two team teaser", "three team parlay", "two team parlay", "two team reverse", "three team reverse"]
				@bet_type = @bet_opt.sample
			
			elsif @teaser_options == 2 && @all_other_options == 2

				@bet_opt = ["two team teaser", "two team parlay", "two team reverse"]
				@bet_type = @bet_opt.sample

			elsif @teaser_options == 0

				if @all_other_options == 2

					@bet_opt = ["two team parlay", "two team reverse"]
					@bet_type = @bet_opt.sample

				elsif @all_other_options == 3

					@bet_opt = ["three team parlay", "two team parlay", "two team reverse", "three team reverse"]
					@bet_type = @bet_opt.sample
				
				elsif @all_other_options == 4

					@bet_opt = ["three team parlay", "two team parlay", "two team reverse", "three team reverse", "four team reverse"]
					@bet_type = @bet_opt.sample
				
				elsif @all_other_options > 4

					@bet_opt = ["three team parlay", "two team parlay", "five team parlay", "two team reverse", "three team reverse", "four team reverse"]
					@bet_type = @bet_opt.sample

				end
			

			end

		elsif obj.bet_types == "Straight"

			@bet_type = "straight"

		end


	end

	def sort_teams_for_leagues

		@teams.each do |t|

			if t.display == "on" && t.date == @my_date

				if t.sport == "NFL"

					@nfl_games.push(t)

				elsif t.sport == "FAN"

					@fan_games.push(t)

				elsif t.sport == "NBA"

					@nba_games.push(t)
				
				elsif t.sport == "CBB"

					@cbb_games.push(t)

				elsif t.sport == "CFB"

					@cfb_games.push(t)

app/views/leagues/_client.html.erb
<% @num = @id_holder.length %>

<% @num = @id_holder.length + 1 %>

<% @num = @num.to_s %>

<% @name = "Client" + @num %>

<%= form_for @client do |l| %>

	<%= l.text_field :league_id, value: @league.id %>
	<%= l.text_field :user_id, value: current_user.id %>
	<div>NAME: <%= l.text_field :league_name, value: @name %></div>
	<div>Stakes: <%= l.text_field :stakes, value: "whale" %></div>
	<div>Wager Type:<%= l.text_field :bet_types, value: "All" %></div>
	<div>Bet Quantity: <%= l.text_field :wager_limit, value: "5" %></div>
	<div>Sports: <%= l.text_field :sports, value: "All" %></div>
	<%= l.submit %>


<% end %>

app/views/leagues/holder.html.erb
<% if @start_time > @my_date.to_i || @start_time == @my_date.to_i %>

	<% @id_holder = [] %>


	<% @league.league_clients.each do |c| %>

		<% if c.user_id.to_i == current_user.id.to_i %>

			<% @id_holder.push(c.user_id) %>

		<% end %>

	<% end %>


<% else %>

	<% if @start_time.to_i == @my_date.to_i %>


		<% @id_holder = [] %>


	<% @league.league_clients.each do |c| %>

		<% if c.user_id.to_i == current_user.id.to_i %>

			<% @id_holder.push(c.user_id) %>

		<% end %>

	<% end %>


	<% if @id_holder.length < @league.clients %>

		<div><%= "LOADING CLIENTS..." %></div>

		<div class = "hide">

			<%= render "client" %>

		</div>

		<script>
			
			new_league_client.submit()


		</script>


	<% end %>


	<div id="league_heading">LEAGUE <%= @league.league_name.upcase %></div>
	<div id="rost_head">MY ROSTER</div>

	<div id="league_show_cont">
	

		<div id="standings_container">STANDINGS

			<% @league_players.each do |s| %>

				<% @sum = [] %>

				<% @bankroll = 0 %>

				<% s.league_wagers.each do |w| %>

					<% if w.league_id.to_i == @league_id.to_i %>

						<% if w.graded == true %>

							<% if w.net_result.to_i > 0 || w.net_result.to_i < 0 %>

								<% @sum.push(w.net_result.to_i) %>

							<% end %>


						<% end %>


					<% end %>

				<% end %>

				<% @stand_info = Hash.new %>

				<% @stand_info[:name] = s.username %>

				<% @bankroll = (@sum.inject(0){|sum,x| sum + x }) * -1 %>

				<% @stand_info[:bank] = @bankroll %>

				<% @scores.push(@stand_info) %>

			<% end %>


			<% self.get_standings(@scores) %>

			<% @off_stand.each do |st| %>

				<% if st.class == Hash %>

					<% if st[:bank].to_i > 0 %>

						<% st[:bank] = "+" + st[:bank].to_s %>

					<% end %>

					<div class="player_standings"><%= st[:name].to_s + " " + st[:bank].to_s %></div>

				<% end %>



			<% end %>

		</div>

		<div id="roster_cont">

			<% @league.league_clients.each do |c| %>

				<% if c.user_id.to_i == current_user.id.to_i %>

					<div class="rost_cont">

						<div class="roster_info", id="lg_nm"> <%= c.league_name %></div>
						<div class="roster_info">Stakes: <%= c.stakes %></div>
						<div class="roster_info">Bet Type: <%= c.bet_types %></div>
						<div class="roster_info">Bet Quant: <%= c.wager_limit %></div>
						<div class="roster_info">Sports: <%= c.sports %></div>


						<div class="roster_links"><%= link_to "CHANGE SETTINGS", edit_league_client_path(c.id) %></div>

					</div>


				<% end %>	

			<% end %>


		</div>

		<div id="league_client_stats">

			<% current_user.league_clients.each do |l| %>



				<% if l.league_id.to_i == @league.id.to_i %>

					<% @client_holder.push(l) %>


				<% end %>


			<% end %>

			<% @client_holder.each do |c| %>


				<% self.sum_league_wagers(c) %>


			<% end %>



			<% @clients_info.each do |c| %>

				<% if c.class == Hash %>

					<% if c[:score] > 0 %>

						<% c[:score] = "+" + c[:score].to_s %>


					<% end %>

					<div class="league_client_score"><%= c[:name] + " " + c[:score].to_s %></div>

				<% end %>


			<% end %>

		</div>



	</div>

	<div id="link_holder">

		<% self.get_time %>

		<% current_user.league_wagers.each do |w| %>

			<% if w.league_id.to_i == @league.id.to_i %>

				<% if w.graded == false %>

					<% if w.date != @my_date %>

						<% @edit_w.push(w) %>


					<% end %>

				<% end %>

			<% end %>

		<% end %>

		<% if @edit_w.length > 0 && @grade_ready == true%>

			 <div class="links"><%= link_to "GRADE YOUR ACTION", edit_league_wager_path(@edit_w[0]) %>


		<% else %>

			<% current_user.league_wagers.each do |w| %>

				<% if w.league_id.to_i == @league.id.to_i %>

					<% if w.graded == false && w.date == @my_date %>

						<% @wager_counter.push(w) %>


					<% end %>


				<% end %>


			<% end %>

			<% current_user.league_clients.each do |c| %>


				<% if c.league_id.to_i == @league.id.to_i %>

					<% @cl_wager_counter = @cl_wager_counter + c.wager_limit.to_i %>


				<% end %>



			<% end %>

			<% if @wager_counter.length < @cl_wager_counter && @book_ready == true %>

				<% @my_id = @league.league_clients[0].id %>
				<div class="links"><%= link_to "BOOK ACTION", league_client_path(@my_id) %>


				<% if @league.league_wagers[0] %>
				
					<% @wager_id = @league.league_wagers[0] %>

					<div class="links"><%= link_to "VIEW LEAGUE ACTION", league_wager_path(@wager_id) %></div>

				<% end %>

			<% else %>

				<% if @league.league_wagers[0] %>

					<% @wager_id = @league.league_wagers[0] %>

					<div class="links"><%= link_to "VIEW LEAGUE ACTION", league_wager_path(@wager_id) %></div>

				<% end %>


			<% end %>




		<% end %>


	</div>

		




</div>


	<% elsif @start_time < @my_date && @end_date_ser >= @my_date %>

		<% @id_holder = [] %>


	<% @league.league_clients.each do |c| %>

		<% if c.user_id.to_i == current_user.id.to_i %>

			<% @id_holder.push(c.user_id) %>

		<% end %>

	<% end %>


	<% if @id_holder.length < @league.clients.to_i %>

		<div><%= "LOADING CLIENTS..." %></div>

		<div class = "hide">

			<%= render "client" %>

		</div>

		<script>
			
			new_league_client.submit()


		</script>


	<% end %>

	<div id="league_heading">LEAGUE <%= @league.league_name.upcase %></div>
	<div id="rost_head">MY ROSTER</div>

	<div id="league_show_cont">

		

		<div id="standings_container">STANDINGS

			<% @users.each do |u| %>


				<% @entrance = false %>

				<% u.league_wagers.each do |w| %>

					<% if w.league_id.to_i == @league.id.to_i  %>

						<% @entrance = true %>


					<% end %>

				<% end %>

				<% if @entrance == true %>

					<% @standings.push(u) %>


				<% end %>

			<% end %>

			<% @standings.each do |s| %>

				<% @sum = [] %>

				<% @bankroll = 0 %>

				<% s.league_wagers.each do |w| %>

					<% if w.league_id.to_i == @league_id.to_i && w.league_client_id.to_s.length > 0 %>


						<% if w.graded == true %>


							<% if w.net_result.to_i > 0 || w.net_result.to_i < 0 %>


								<% @sum.push(w.net_result.to_i) %>

							<% end %>


						<% end %>


					<% end %>

				<% end %>


				<% @stand_info = Hash.new %>

				<% @stand_info[:name] = s.username %>


				<% @bankroll = @sum.inject(0){|sum,x| sum + x } %>

				<% @bankroll = @bankroll * -1 %>

				<% @stand_info[:bank] = @bankroll %>

				<% @scores.push(@stand_info) %>

			<% end %>


			<% self.get_standings(@scores) %>

			<% @off_stand.each do |st| %>

				<% if st.class == Hash %>

					<% if st[:bank].to_i > 0 %>

						<% st[:bank] = "+" + st[:bank].to_s %>

					<% end %>

					<div class="player_standings"><%= st[:name].to_s + " " + st[:bank].to_s %></div>

				<% end %>



			<% end %>

		</div>

		<div id="roster_cont">

			<% @league.league_clients.each do |c| %>

				<% if c.user_id.to_i == current_user.id.to_i %>

					<div class="rost_cont">

						<div class="roster_info", id="lg_nm"> <%= c.league_name %></div>
						<div class="roster_info">Stakes: <%= c.stakes %></div>
						<div class="roster_info">Bet Type: <%= c.bet_types %></div>
						<div class="roster_info">Bet Quant: <%= c.wager_limit %></div>
						<div class="roster_info">Sports: <%= c.sports %></div>


						<div class="roster_links"><%= link_to "CHANGE SETTINGS", edit_league_client_path(c.id) %></div>

					</div>


				<% end %>	

			<% end %>


		</div>

		<div id="league_client_stats">

			<% current_user.league_clients.each do |l| %>



				<% if l.league_id.to_i == @league.id.to_i %>

					<% @client_holder.push(l) %>


				<% end %>


			<% end %>

			<% @client_holder.each do |c| %>


				<% self.sum_league_wagers(c) %>


			<% end %>



			<% @clients_info.each do |c| %>

				<% if c.class == Hash %>

					<% if c[:score].to_i > 0 %>

						<% c[:score] = "+" + c[:score].to_s %>

					<% end %>

					<div class="league_client_score"><%= c[:name] + " " + c[:score].to_s %></div>

				<% end %>


			<% end %>

		</div>



	</div>



	<div id="link_holder">

		<% self.get_time %>

		<% current_user.league_wagers.each do |w| %>

			<% if w.league_id.to_i == @league.id.to_i %>

				<% if w.graded == false %>

					<% if w.date != @my_date %>

						<% @edit_w.push(w) %>


					<% end %>

				<% end %>

			<% end %>

		<% end %>


		<% if @edit_w.length > 0 %>

			 <div class="links"><%= link_to "GRADE YOUR ACTION", edit_league_wager_path(@edit_w[0]) %> 


		<% else %>

			<% current_user.league_wagers.each do |w| %>

				<% if w.league_id.to_i == @league.id.to_i %>

					<% if w.graded == false && w.date == @my_date %>

						<% @wager_counter.push(w) %>


					<% end %>


				<% end %>


			<% end %>

			<% current_user.league_clients.each do |c| %>


				<% if c.league_id.to_i == @league.id.to_i %>

					<% @cl_wager_counter = @cl_wager_counter + c.wager_limit.to_i %>


				<% end %>



			<% end %>

			<% if @wager_counter.length < @cl_wager_counter %>

				<% @my_id = @league.league_clients[0].id %>
				<div class="links"><%= link_to "BOOK ACTION", league_client_path(@my_id) %>


				<% if @league.league_wagers[0] %>
				
					<% @wager_id = @league.league_wagers[0] %>

					<div class="links"><%= link_to "VIEW LEAGUE ACTION", league_wager_path(@wager_id) %></div>

				<% end %>

			<% else %>

				<% if @league.league_wagers[0] %>

					<% @wager_id = @league.league_wagers[0] %>

					<div class="links"><%= link_to "VIEW LEAGUE ACTION", league_wager_path(@wager_id) %></div>

				<% end %>


			<% end %>




		<% end %>

	</div>

		




</div>


	<% elsif @start_time < @my_date && @end_date_ser < @my_date %>

		<div id="standings_container">STANDINGS

			<% @users.each do |u| %>

				<% @entrance = false %>

				<% u.league_wagers.each do |w| %>

					<% if w.league_id.to_i == @league.id.to_i %>

						<% @entrance = true %>


					<% end %>

				<% end %>

				<% if @entrance == true %>

					<% @standings.push(u) %>


				<% end %>

			<% end %>

			<% @standings.each do |s| %>

				<% @sum = [] %>

				<% @bankroll = 0 %>

				<% s.league_wagers.each do |w| %>

					<% if w.league_id.to_i == @league_id.to_i %>

						<% if w.graded == true %>

							<% if w.net_result.to_i > 0 || w.net_result.to_i < 0 %>

								<% @sum.push(w.net_result.to_i) %>

							<% end %>


						<% end %>


					<% end %>

				<% end %>

				<% @stand_info = Hash.new %>

				<% @stand_info[:name] = s.username %>

				<% @bankroll = @sum.inject(0){|sum,x| sum + x } %>

				<% @bankroll = @bankroll * -1 %>

				<% @stand_info[:bank] = @bankroll %>

				<% @scores.push(@stand_info) %>

			<% end %>


			<% self.get_standings(@scores) %>

			<% @off_stand.each do |st| %>

				<% if st.class == Hash %>

					<% if st[:bank].to_i > 0 %>

						<% st[:bank] = "+" + st[:bank].to_s %>

					<% end %>

					<div class="player_standings"><%= st[:name].to_s + " " + st[:bank].to_s %></div>

				<% end %>



			<% end %>

		</div>

	
	<% end %> 


<% end %>