config/routes.rb
Rails.application.routes.draw do

resources :teams
resources :leagues
resources :league_clients
resources :league_wagers
resources :secrets
resources :players
resources :pools
resources :groups
resources :selections
resources :tickets


get "users/profile" => "welcome#users_show"
get "game/rules" => "welcome#rules"










devise_for :users, :controllers => { :registrations => 'users/registrations' }
devise_scope :user do
  authenticated :user do
    root :to => "welcome#users_show", as: :authenticated_root
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def show

		@user = current_user

	end

	def index



		

	end

	def test

	end

	def users_show

		

	end

	def rules


	end


end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def sum_pending

		current_user.wagers.each do |w|

			if w.date == @my_date

				@pending_action = @pending_action + w.amount.to_i

			end

		end

	end

	def get_leagues

		current_user.secrets.each do |s|

			@secrets_cont.push(s.pass) unless @secrets_cont.include?(s.pass)

		end

	end

	def sort_selections

		if @pool.groups.count != 0

			@pool.groups.each do |g|

				graded = []
				ungraded = []

				g.selections.each do |s|

					if s.result == "none"

						ungraded.push(s)

					else

						graded.push(s)

					end


				end

				if ungraded.length > 0

					@active_pools.push(@pool) unless @active_pools.include?(@pool)


				end


			end


		end

	end
end

app/views/welcome/rules.html.erb
<div id="game_master">

	<div id="game_heading">
		
		<p>GAME RULES</p>

	</div>

	<div id="rules_holder">

		<div class="game_cont">
		
			<div class="game_head">BOOKIE WARS</div>

			<div class="game_text">
				
				<p>Bookie Wars is a fantasy game that is played in league format.  Leagues have a start date and an end date.  Particpants in the league start with the same number of sports betting clients.  Each participant is in charge of setting or changing the attributes of their clients.  All clients have three different type settings, three frequency settings, eight settings for sport, and three settings for stakes.  Settings can be changed daily.  Once their roster is set, entrants will book the daily action of their client list and a tally on profit is kept for each entrant.  The entrant with the post profit at the end of the league wins.</p>

				<p>Type Settings</p>

				<p>1. Straight</p>
				<p>2. Exotic</p>
				<p>3. All</p>


			</div>

		</div>

		<div class="game_cont">
		
			<div class="game_head">FANISIDE POOLS</div>

		</div>

		<div class="game_text">
				
				<p></p>


			</div>






	</div>









</div>

app/views/welcome/show.html.erb
USER PROFILE

app/views/welcome/users_show.html.erb
<div id="styling_background">
	<% @secrets_cont = [] %>

	<% @users_leagues = [] %>
	<% @users_pools = [] %>
	<% @completed_pools = [] %>
	<% @completed_leagues = [] %>
	<% @active_leagues = [] %>
	<% @active_pools = [] %>
	<% @contestants = [] %>
	<% @pool_players = [] %>
	<% @pool_standings = [] %>
	<% @eliminated = [] %>
	<% @still_alive = [] %>
	<% @winners = [] %>
	<% @losers = [] %>
	<% @wager_total = 0 %>
	<% @my_date %>
	<% @serial_num_check %>
	<% @wagers_backed = current_user.league_wagers.count %>
	<% @total = 0 %>
	<% @straight_bets = 0 %>
	<% @parlay_bets = 0 %>
	<% @two_team_parlay_bets = 0 %>
	<% @three_team_parlay_bets = 0 %>
	<% @five_team_parlay_bets = 0 %>
	<% @teaser_bets = 0 %>
	<% @two_team_teaser_bets = 0 %>
	<% @three_team_teaser_bets = 0 %>
	<% @five_team_teaser_bets = 0 %>
	<% @reverse_bets = 0 %>
	<% @two_team_reverse_bets = 0 %>
	<% @three_team_reverse_bets = 0 %>
	<% @four_team_reverse_bets = 0 %>
	<% @straight_results = [] %>
	<% @two_t_results = [] %>
	<% @three_t_results = [] %>
	<% @five_t_results = [] %>
	<% @two_p_results = [] %>
	<% @three_p_results = [] %>
	<% @five_p_results = [] %>
	<% @two_r_results = [] %>
	<% @three_r_results = [] %>
	<% @four_r_results = [] %>
	<% @str_sum %>
	<% @two_p_sum %>
	<% @three_p_sum %>
	<% @five_p_sum %>
	<% @two_t_sum %>
	<% @three_t_sum %>
	<% @five_t_sum %>
	<% @two_r_sum %>
	<% @three_r_sum %>
	<% @four_r_sum %>
	<% @new_pool = false %>
	<% @show_league = false %>
	<% @id_holder = [] %>
	<% @pool_id_holder = [] %>



	<% self.get_leagues %>

	<% self.get_time %>

	<% self.convert_date(@my_date) %>

	<% @my_date = @serial_num_check %>








	<% League.all.each do |l| %>

		<% @secrets_cont.each do |s| %>

			<% if l.pass == s %>

				<% @users_leagues.push(l) %>


			<% end %>


		<% end %>

	<% end %>

	<div>
		

		<% Pool.all.each do |p| %>

			<% @secrets_cont.each do |s| %>

				<% if p.pass == s %>

					<% @users_pools.push(p) %>			

				<% end %>


			<% end %>

		<% end %>


	</div>



	<div>

		<% @users_leagues.each do |l| %>

			<% @show_league = false %>

			<% if l.end_date.length == 11 %>

				<% self.convert_date(l.end_date) %>

				<% if @serial_num_check < @my_date %>

					<% @completed_leagues.push(l) %>

				<% else %>

					<% @active_leagues.push(l) %>

				<% end %>

			<% end %>

			<% l.league_wagers.each do |w| %>

				<% if w.graded == false %>

					<% @show_league = true %>

				<% end %>


			<% end %>

			<% if @show_league == true %>

				<% @active_leagues.push(l) unless @active_leagues.include?(l) %>

			<% end %>

		<% end %>


		<% self.get_time %>

		<% @users_pools.each do |p| %>

			<% @still_alive = [] %>
			<% @pool_players = [] %>
			<% @pool_standings = [] %>
			<% @eliminated = [] %>
			<% @contestants = [] %>
			<% @still_in %>

			<% @pool = p %>

			<% if @pool.groups.count == 1 && @pool.groups.last.date == @my_date %>
		
				<% @new_pool = true %>

			<% elsif @pool.groups.count == 0 %>

				<% @new_pool = true %>

			<% end %>



			<% if @new_pool == true %>

				<% @active_pools.push(p) unless @active_pools.include?(p) %>

			<% end %>


			<% self.get_pool_players %>
			<% self.get_all_selections %>
			<% self.get_remaining_contestants %>
			<% self.sort_selections %>


			<% if @still_alive.length > 1 %>

				<% @active_pools.push(p) unless @active_pools.include?(p) %>

			<% elsif @still_alive.length == 1 %>

				<% @selec = 0 %>

				<% @pool.selections.each do |s| %>

					<% if s.result != "none" %>

						<% @selec = @selec + 1 %>

					<% end %>


				<% end %>

				<% if @selec == 0 %>

					<% @active_pools.push(p) unless @active_pools.include?(p) %>

				<% end %>


			<% else %>

				<% @completed_pools.push(p) %>

			<% end %>


		<% end %>


		<% self.get_wager_types %>


	</div>


	<div id="profile_cont">
		
		<div id="profile_leagues" class="prof_cont">

			<div id="active_leagues"><div class="prof_label" id="league_label">ACTIVE LEAGUES</div>

					<% @active_leagues.each do |l| %>

						<div class="pool_links"><%=link_to l.league_name.upcase, league_path(l.id) %></div>

					<% end %>

			</div>

			<div id="league_stats"><div class = "prof_label" id="league_stats">LEAGUE STATS</div>

				<% current_user.league_wagers.each do |w| %>

					<% @id_holder.push(w.league_id) unless @id_holder.include?(w.league_id) %>


					<% if w.net_result.to_i > 0 || w.net_result.to_i < 0 %>

						<% @total = @total + (w.net_result.to_i * -1) %>

					<% end %>

				<% end %>

				<% if @total > 0 %>


					<% @total = "+" + @total.to_s %>

				<% end %>

				<div id="num_cont">

					<div>Leagues Played In: <%= @id_holder.length %></div>

					
					<div>Wagers Backed: <%= @wagers_backed %></div>
					
					<div>Straight Wagers: <%= @straight_results.length %> booked.  <%= @str_sum %> profit. </div>

					<div>Two Team Parlays: <%= @two_p_results.length %> booked.  <%= @two_p_sum %> profit. </div>

					<div>Three Team Parlays: <%= @three_p_results.length %> booked.  <%= @three_p_sum %> profit. </div>

					<div>Five Team Parlays: <%= @five_p_results.length %> booked.  <%= @five_p_sum %> profit. </div>

					<div>Two Team Teasers: <%= @two_t_results.length %> booked.  <%= @two_t_sum %> profit. </div>

					<div>Three Team Teasers: <%= @three_t_results.length %> booked.  <%= @three_t_sum %> profit. </div>

					<div>Five Team Teasers: <%= @five_t_results.length %> booked.  <%= @five_t_sum %> profit. </div>

					<div>Two Team Reverses: <%= @two_r_results.length %> booked.  <%= @two_r_sum %> profit. </div>

					<div>Three Team Reverses: <%= @three_r_results.length %> booked.  <%= @three_r_sum %> profit. </div>

					<div>Four Team Reverses: <%= @four_r_results.length %> booked.  <%= @four_r_sum %> profit. </div>

					<div id="prof_total">Total Profit: <%= @total %></div>

				</div>


			</div>


		</div>

		<div id="profile_pools" class="prof_cont">

			<div id="active_pools"><div class = "prof_label" id="pool_label">ACTIVE POOLS</div>

				<% @active_pools.each do |p| %>



					<div class="pool_links"><%=link_to p.pool_name.upcase, pool_path(p.id) %></div>

				<% end %>

			</div>

			<div id="pool_stats"><div class = "prof_label" id="pool_st">POOL STATS</div>

				<div id="centering_box">

					<% current_user.selections.each do |s| %>

						<% @pool_id_holder.push(s.pool_id) unless @pool_id_holder.include?(s.pool_id) %>
			
						<% if s.result == "winner" %>

							<% @winners.push(s) %>

						<% elsif s.result == "loser" %>

							<% @losers.push(s) %>

						<% end %>

					<% end %>

					<% @wins = @winners.length %>
					<% @total = @losers.length + @winners.length %>

					<% @percentage = @wins.to_f/@total.to_f * 100 %>


					<div> Pools Played In: <%= @pool_id_holder.length %></div>
					<div>Selections Made: <%= @total %></div>

					<div>Wins: <%= @wins %></div>
					<div>Losses: <%= @losers.length %></div>

					<div>Percentage: <%= @percentage.to_s + "%" %></div>

				</div>


			</div>

			



		</div>




	</div>
</div>

<div>
	
	<% if current_user.admin == true %>

		<div style="margin-top: 20px; margin-bottom: 10px;">USERS: <%= User.all.count %></div>
		
		<div style="margin-top: 20px; margin-bottom: 10px;">USERS EMAILS: <% User.all.each do |u| %>

				<div><%= u.email %></div>

			<% end %>
			

		</div>
		
		<div style="margin-bottom: 10px;">POOLS: <%= Pool.all.count %></div>
		
		<div style="margin-bottom: 10px;">LEAGUES: <%= League.all.count %></div>

	<% end %>




</div>

























	