config/routes.rb
Rails.application.routes.draw do

resources :teams
resources :leagues
resources :league_clients
resources :league_wagers
resources :secrets
resources :players
resources :pools
resources :groups
resources :selections
resources :tickets


get "users/profile" => "welcome#users_show"
get "game/rules" => "welcome#rules"










devise_for :users, :controllers => { :registrations => 'users/registrations' }
devise_scope :user do
  authenticated :user do
    root :to => "welcome#users_show", as: :authenticated_root
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord

	has_many :tickets
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController


	def new
		
		@player = Player.new

	end

	def create

		player = Player.new(player_params)

		if player.save

			redirect_to players_path

		else

			redirect_back(fallback_location: players_path)

		end

	end

	def index

		@players = Player.all
		@tickets = Ticket.all

	end

	def edit

		@player = Player.find_by_id(params[:id])
		@ticket = Ticket.new 

	end

	private

	def player_params

	params.require(:player).permit(:name, :sport, :rating)

	end

	def ticket_params

		params.require(:ticket).permit(:date, :player_id, :name, :rating, :sport, :def_rating, :pitcher, :score)

	end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<% @my_date %>

<% self.get_time %>

<%= form_for @ticket do |t| %>

	<div>DATE: <%= t.text_field :date, :value => @my_date %></div>
	<div><%= t.hidden_field :player_id, :value => @player.id %></div>
	<div>NAME: <%= t.text_field :name, :value => @player.name %></div>
	<div>SPORT: <%= t.text_field :sport, :value => @player.sport %></div>
	<div>SCORE: <%= t.text_field :score %></div>
	<div><%= t.submit %></div>

<% end %>

app/views/players/index.html.erb
<div id="players_cont">
	
	<div class="sport" id="nfl_players">NFL PLAYERS

		<% @players.each do |p| %>

			<% if p.sport == "NFL" %>

				<div style="margin-top: 8%;"><%= link_to p.name, edit_player_path(p.id) %></div>

			<% end %>
		
		<% end %>
		


	</div>
	<div class="sport" id="nba_players">NBA PLAYERS

		<% @players.each do |p| %>

			<% if p.sport == "NBA" %>

				<div style="margin-top: 8%;"><%= link_to p.name, edit_player_path(p.id) %></div>

			<% end %>
		
		<% end %>
		


	</div>
	<div class="sport" id="mlb_players">MLB PLAYERS

		<% @players.each do |p| %>

			<% if p.sport == "MLB" %>

				<div style="margin-top: 8%;"><%= link_to p.name, edit_player_path(p.id) %></div>

			<% end %>
		
		<% end %>
		


	</div>

	<div style="display: inline-block; vertical-align: top; margin-top: 3%;"><%= link_to "NEW PLAYER", new_player_path %></div>







</div>

app/views/players/new.html.erb
<%= form_for @player do |p| %>

	<div>NAME: <%= p.text_field :name %></div>
	<div>SPORT: <%= p.text_field :sport %></div>
	<div><%= p.submit %></div>



<% end %>