config/routes.rb
Rails.application.routes.draw do

resources :teams
resources :leagues
resources :league_clients
resources :league_wagers
resources :secrets
resources :players
resources :pools
resources :groups
resources :selections
resources :tickets


get "users/profile" => "welcome#users_show"
get "game/rules" => "welcome#rules"










devise_for :users, :controllers => { :registrations => 'users/registrations' }
devise_scope :user do
  authenticated :user do
    root :to => "welcome#users_show", as: :authenticated_root
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="pic">
  
      <p>WELCOME TO FANBOUTS.COM</p>
  
    </div>


    <% @my_client %>
    <% self.get_access %>

    <div id="navbar">

      <% if !current_user %>

        <div class ="nav_links"><%= link_to "Sign Up", new_user_registration_path, class: 'link_tabs'  %></div>
        <div class ="nav_links"><%= link_to "HOME", user_session_path, class: 'link_tabs'  %></div>

      <% elsif current_user && current_user.admin == true %>

          <div class ="nav_links"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'link_tabs'  %></div>

          
          <div class ="nav_links"><%= link_to "MY PROFILE", users_profile_path, class: 'link_tabs'  %></div>
          
          <div class ="nav_links"><%= link_to "PLAY BOOKIE WARS", leagues_path %></div>
          <div class ="nav_links"><%= link_to "PLAY FANICIDE POOLS", pools_path %></div>
          <div class ="nav_links"><%= link_to "New Team", new_team_path, class: 'link_tabs'  %></div>
          <div class ="nav_links"><%= link_to "Team List", teams_path, class: 'link_tabs'  %></div>
          <div class ="nav_links"><%= link_to "Player List", players_path, class: 'link_tabs'  %></div>
          <div class ="nav_links"><%= link_to "Open Tickets", tickets_path, class: 'link_tabs'  %></div>


      <% else %>
     

      	<div class ="nav_links"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'link_tabs'  %></div>

      
        <div class ="nav_links"><%= link_to "MY PROFILE", users_profile_path, class: 'link_tabs'  %></div>
        <div class ="nav_links"><%= link_to "PLAY BOOKIE WARS", leagues_path %></div>
        <div class ="nav_links"><%= link_to "PLAY FANICIDE POOLS", pools_path %></div>

      <% end %>

    </div>

  	
    <%= yield %>
  </body>
</html>